""" APT payload key names and values"""

GH_CREAT_REPO_REPO_NAME_KEY = "repo_name"
GH_CREAT_REPO_COLLABORATOR_NAME_KEY = "collaborator_name"
GH_CREAT_REPO_IS_PRIVATE_KEY = "is_private"
GH_USERNAME = "username"
GH_TOKEN = "token"
GH_CREATE_DATA = "content"

GH_ANALYSE_REPO_LIST = "repo_names"
GH_ANALYSE_REPO_LIST_NAME = "name"
GH_ANALYSE_REPO_LIST_ST_DT = "start_date"
GH_ANALYSE_REPO_LIST_ED_DT = "end_date"
GH_ANALYSE_INTEGRATE_TAIGA = "integrate_taiga"
GH_ANALYSE_TAIGA_USERNAME = "tg_username"
GH_ANALYSE_TAIGA_PASSWORD = "tg_password"

# sent by GitHub API
GH_API_USERNAME = "login"
GH_API_AUTHOR = "author"
GH_API_AUTHOR_DISPLAY = "name"
GH_API_COMMIT = "commit"
GH_API_COMMIT_DT = "date"
GH_API_COMMITTER = "committer"
GH_API_COMMIT_MESSAGE = "message"
GH_API_COMMIT_CMT_CNT = "comment_count"
GH_API_COMMIT_SHA = "sha"
GH_API_COMMIT_URL = "url"
GH_API_COMMIT_STATS = "stats"
GH_API_PR_NUM = "number"
GH_API_PR_URL = "url"
GH_API_PR_STATE = "state"
GH_API_PR_TITLE = "title"
GH_API_PR_BODY = "body"
GH_API_PR_CR_DT = "created_at"
GH_API_PR_CL_DT = "closed_at"
GH_API_PR_MR_DT = "merged_at"
# user that opened the PR
GH_API_PR_USER = "user"
GH_API_PR_USERNAME = "login"
# user(s) that was assigned to the PR
GH_API_PR_ASG = "assignees"
GH_API_PR_REV = "requested_reviewers"
GH_API_PR_BASE = "base"
GH_API_PR_HEAD = "head"
GH_API_PR_REF = "ref"
GH_API_PR_URL = "url"
GH_API_BRANCH_NAME = "name"

GH_API_COMMIT_ADD = "additions"
GH_API_COMMIT_DEL = "deletions"
GH_API_COMMIT_TOT = "total"

GH_API_PR_COMMENTS = "comments"
GH_API_PR_REV_COMMENTS = "review_comments"
GH_API_PR_COMMITS = "commits"
GH_API_PR_ADD = "additions"
GH_API_PR_DEL = "deletions"
GH_API_PR_FILES = "changed_files"
