""" APT payload key names and values"""

# controlled by this project
TG_PROJECT_NAME = "project_name"
TG_PROJECT_SLUG = "project_slug"
TG_PROJECT_DESC = "project_description"
TG_MEMBER_NAME = "member_name"
TG_MEMBER_USERNAME = "member_username"
TG_MEMBERS = "members"
TG_ERROR = "error"
TG_ERROR_MESSAGE = "message"

# controlled by Taiga API
TG_API_PROJECT_NAME = "name"
TG_API_PROJECT_DESC = "description"
TG_API_PROJECT_SLUG = "slug"
TG_API_PROJECT_ID = "project_id"
TG_API_MEMBERS = "bulk_memberships"
TG_API_ROLE_ID = "role_id"
TG_API_ROLES = "roles"

# common - used by both
TG_USERNAME = "username"
TG_PASSWORD = "password"
TG_AUTH_TOKEN = "auth_token"
TG_USER_ID = "user_id"
TG_PROJECT_ID = "id"
TG_PROJECT_PRIVACY = "is_private"

# used by analyse API
TG_ANLS_RP_LST = "board_names"
TG_ANLS_RP_LST_NAME = "name"
TG_EXPORT_DONE = "url"
TG_EXPORT_REQUESTED = "export_id"
# Project Details
TG_ANLS_PRJ_MEM = "members"
TG_ANLS_PRJ_NAME = "name"
TG_ANLS_PRJ_MEM_NAME = "full_name_display"
TG_ANLS_PRJ_MEM_UNAME = "username"
TG_ANLS_PRJ_MEM_ID = "id"
# Milestones
TG_ANLS_PRJ_MS = "milestones"
TG_ANLS_PRJ_MS_ID = "id"
TG_ANLS_PRJ_MS_NAME = "name"
TG_ANLS_PRJ_MS_SLUG = "slug"
TG_ANLS_PRJ_MS_CLS = "closed"
TG_ANLS_PRJ_MS_US = "user_stories"
TG_ANLS_PRJ_MS_CLS_PTS = "closed_points"
TG_ANLS_PRJ_MS_TOT_PTS = "total_points"
TG_ANLS_PRJ_MS_CR_DT = "created_date"
TG_ANLS_PRJ_MS_MD_DT = "modified_date"
TG_ANLS_PRJ_MS_EST_FIN = "estimated_finish"
TG_ANLS_PRJ_MS_EST_SRT = "estimated_start"
# User Story
TG_ANLS_PRJ_US_ID = "id"
TG_ANLS_PRJ_US_ASG_INFO = "assigned_to_extra_info"
TG_ANLS_PRJ_US_ASG_TO = "username"
TG_ANLS_PRJ_US_FIN_DT = "finish_date"
TG_ANLS_PRJ_US_CR_DT = "created_date"
TG_ANLS_PRJ_US_MD_DT = "modified_date"
TG_ANLS_PRJ_US_IS_CLS = "is_closed"
TG_ANLS_PRJ_US_STS_INFO = "status_extra_info"
TG_ANLS_PRJ_US_STS_NAME = "name"
TG_ANLS_PRJ_US_SUB = "subject"
TG_ANLS_PRJ_US_TOT_PTS = "total_points"
# TG_ANALYSE_PROJECT_MEMBER_ROLE = "role_name"
# TG_ANALYSE_PROJECT_MEMBER_ROLE_ID = "role"
